baseurl = "http://chillerby-dev.s3-website.eu-west-2.amazonaws.com/"
languageCode = "en-us"
theme = "hello-friend-ng"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "content/posts"

  # Default theme "light" or "dark"
  defaultTheme = "dark"

  [[params.social]]
    name = "github"
    url  = "https://github.com/chillerby"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/connor-hillerby-80660282/"

[languages]
  [languages.en]
    title = "Welcome to my website!"
    subtitle = "A simple theme for Hugo"
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "$ cd ~/"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

[deployment]
  # By default, files are uploaded in an arbitrary order.
  # Files that match the regular expressions in the "Order" list
  # will be uploaded first, in the listed order.
  # order = [".jpg$", ".gif$"]


  [[deployment.targets]]
    # An arbitrary name for this target.
    name = "connor.hillerby.com"
    # The Go Cloud Development Kit URL to deploy to. Examples:
    # GCS; see https://gocloud.dev/howto/blob/#gcs
    # URL = "gs://<Bucket Name>"

    # S3; see https://gocloud.dev/howto/blob/#s3
    # For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
    URL = "s3://connor.hillerby.com?region=eu-west-2"

    # Azure Blob Storage; see https://gocloud.dev/howto/blob/#azure
    # URL = "azblob://$web"

    # You can use a "prefix=" query parameter to target a subfolder of the bucket:
    # URL = "gs://<Bucket Name>?prefix=a/subfolder/"

    # If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
    # cloudFrontDistributionID = <ID>


    # ... add more [[deployment.targets]] sections ...


    # [[deployment.matchers]] configure behavior for files that match the Pattern.
    # Samples:

  #[[deployment.matchers]]
    #  Cache static assets for 1 year.
  #  pattern = "^.+\\.(js|css|svg|ttf)$"
  #  cacheControl = "max-age=31536000, no-transform, public"
  #  gzip = true

  #[[deployment.matchers]]
  #  pattern = "^.+\\.(png|jpg)$"
  #  cacheControl = "max-age=31536000, no-transform, public"
  #  gzip = false

  #[[deployment.matchers]]
  #  pattern = "^.+\\.(html|xml|json)$"
  #  gzip = true